<?php

namespace Cupon\CiudadBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CiudadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CiudadRepository extends EntityRepository
{
	public function findCercanas($ciudad_id)
	{
		$em = $this->getEntityManager();
		$consulta = $em->createQuery('
			SELECT c
			FROM CiudadBundle:Ciudad c
			WHERE c.id != :id
			ORDER BY c.nombre ASC');
		$consulta->setMaxResults(5);
		$consulta->setParameter('id', $ciudad_id);
		return $consulta->getResult();
	}
}

