_portada:
    path: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: portada, ciudad: '%cupon.ciudad_por_defecto%' }

portada:
    path: /{ciudad}
    defaults: { _controller: OfertaBundle:Default:portada }

usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /usuario

tienda:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /

extranet:
    resource: "@TiendaBundle/Resources/config/extranet/routing.yml"
    prefix:   /extranet

#oferta:
 #   resource: "@OfertaBundle/Resources/config/routing.yml"
  #  prefix:   /

pagina_ayuda:
    path: /ayuda/
    defaults: { _controller: OfertaBundle:Default:ayuda }

pagina_estatica:
    path: /post/{pagina}/
    defaults: { _controller: OfertaBundle:Post:verPagina}

ciudad_cambiar:
    pattern: /ciudad/cambiar-a-{ciudad}
    defaults: { _controller: CiudadBundle:Default:cambiar }
    requirements:
        ciudad: .+

oferta:
    path: /{ciudad}/ofertas/{slug}
    defaults: { _controller: OfertaBundle:Default:oferta }

ciudad_recientes:
    path: /{ciudad}/recientes
    defaults: { _controller: CiudadBundle:Default:recientes }

tienda_portada:
    path: /{ciudad}/tiendas/{tienda}
    defaults: { _controller: TiendaBundle:Default:portada }




