usuario_homepage:
    path:     /hello/{name}
    defaults: { _controller: UsuarioBundle:Default:index }

usuario_compras:
    path: /compras
    defaults: { _controller: UsuarioBundle:Default:compras }
